export const FakeDataGameProcess = [
    {
        game: {
            gameId: 1026946,
            result: -2,
            gameIdEncode: "BWAOKS",
            deckHistory: "2121212111212111112211122121122211211121",
            time: 20,
            status: 0,
        },
        newName: "1-Fabiola",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "X9RZBzxqA4oY0NuiueHoMzLlGPqnNK",
            tie: 8,
            playerSide: 20,
            balance: 49990,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1026946,
            result: -2,
            gameIdEncode: "BWAOKS",
            deckHistory: "2121212111212111112211122121122211211121",
            time: 2,
            status: 0,
        },
        newName: "1-Fabiola",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "X9RZBzxqA4oY0NuiueHoMzLlGPqnNK",
            tie: 8,
            playerSide: 20,
            balance: 49965,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 5, betOn: 2, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 1, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 0, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "real", username: "ptest1" },
                ],
            },
        },
    },

    {
        game: {
            gameId: 1026946,
            result: -2,
            gameIdEncode: "BWAOKS",
            deckHistory: "2121212111212111112211122121122211211121",
            time: -1,
            banker: {
                Card: [
                    { face: "H", value: 5 },
                    { face: "C", value: 5 },
                ],
            },
            player: {
                Card: [
                    { face: "H", value: 10 },
                    { face: "C", value: 2 },
                    { face: "D", value: "Q" },
                ],
            },
            status: 1,
        },
        newName: "1-Fabiola",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "X9RZBzxqA4oY0NuiueHoMzLlGPqnNK",
            tie: 8,
            playerSide: 20,
            balance: 40000,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 5, betOn: 2, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 1, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 0, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "real", username: "ptest1" },
                ],
            },
        },
    },

    {
        game: {
            gameId: 1026946,
            result: 0,
            playerSide: false,
            gameIdEncode: "BWAOKS",
            deckHistory: "21212121112121111122111221211222112111210",
            time: -1,
            banker: {
                Card: [
                    { face: "H", value: 5 },
                    { face: "C", value: 5 },
                    { face: "C", value: 2 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "H", value: 10 },
                    { face: "C", value: 2 },
                    { face: "D", value: "Q" },
                ],
            },
            status: 2,
        },
        newName: "1-Fabiola",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "X9RZBzxqA4oY0NuiueHoMzLlGPqnNK",
            tie: 8,
            playerSide: 20,
            balance: 50020,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 5, betOn: 2, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 1, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 0, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "real", username: "ptest1" },
                ],
            },
            finalResult: { lost: 10, won: 40, totalBet: 25, commission: 0, totalEarning: 30 },
        },
    },

    {
        game: {
            gameId: 1026946,
            result: 0,
            playerSide: false,
            gameIdEncode: "BWAOKS",
            deckHistory: "21212121112121111122111221211222112111210",
            time: 5,
            banker: {
                Card: [
                    { face: "H", value: 5 },
                    { face: "C", value: 5 },
                    { face: "C", value: 2 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "H", value: 10 },
                    { face: "C", value: 2 },
                    { face: "D", value: "Q" },
                ],
            },
            status: 2,
        },
        newName: "1-Fabiola",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "X9RZBzxqA4oY0NuiueHoMzLlGPqnNK",
            tie: 8,
            playerSide: 20,
            balance: 50020,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 5, betOn: 2, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 1, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 0, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "real", username: "ptest1" },
                ],
            },
            finalResult: { lost: 10, won: 40, totalBet: 25, commission: 0, totalEarning: 30 },
        },
    },

    {
        game: {
            gameId: 1026946,
            result: 0,
            playerSide: false,
            gameIdEncode: "BWAOKS",
            deckHistory: "21212121112121111122111221211222112111210",
            time: 4,
            banker: {
                Card: [
                    { face: "H", value: 5 },
                    { face: "C", value: 5 },
                    { face: "C", value: 2 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "H", value: 10 },
                    { face: "C", value: 2 },
                    { face: "D", value: "Q" },
                ],
            },
            status: 2,
        },
        newName: "1-Fabiola",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "X9RZBzxqA4oY0NuiueHoMzLlGPqnNK",
            tie: 8,
            playerSide: 20,
            balance: 50020,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 5, betOn: 2, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 1, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 0, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "real", username: "ptest1" },
                ],
            },
            finalResult: { lost: 10, won: 40, totalBet: 25, commission: 0, totalEarning: 30 },
        },
    },

    {
        game: {
            gameId: 1026946,
            result: 0,
            playerSide: false,
            gameIdEncode: "BWAOKS",
            deckHistory: "21212121112121111122111221211222112111210",
            time: 3,
            banker: {
                Card: [
                    { face: "H", value: 5 },
                    { face: "C", value: 5 },
                    { face: "C", value: 2 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "H", value: 10 },
                    { face: "C", value: 2 },
                    { face: "D", value: "Q" },
                ],
            },
            status: 2,
        },
        newName: "1-Fabiola",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "X9RZBzxqA4oY0NuiueHoMzLlGPqnNK",
            tie: 8,
            playerSide: 20,
            balance: 50020,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 5, betOn: 2, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 1, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 0, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "real", username: "ptest1" },
                ],
            },
            finalResult: { lost: 10, won: 40, totalBet: 25, commission: 0, totalEarning: 30 },
        },
    },

    {
        game: {
            gameId: 1026946,
            result: 0,
            playerSide: false,
            gameIdEncode: "BWAOKS",
            deckHistory: "21212121112121111122111221211222112111210",
            time: 2,
            banker: {
                Card: [
                    { face: "H", value: 5 },
                    { face: "C", value: 5 },
                    { face: "C", value: 2 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "H", value: 10 },
                    { face: "C", value: 2 },
                    { face: "D", value: "Q" },
                ],
            },
            status: 2,
        },
        newName: "1-Fabiola",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "X9RZBzxqA4oY0NuiueHoMzLlGPqnNK",
            tie: 8,
            playerSide: 20,
            balance: 50020,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 5, betOn: 2, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 1, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 0, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "real", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "real", username: "ptest1" },
                ],
            },
            finalResult: { lost: 10, won: 40, totalBet: 25, commission: 0, totalEarning: 30 },
        },
    },

    {
        game: {
            gameId: 1026947,
            result: -2,
            gameIdEncode: "BWAOL0",
            deckHistory: "21212121112121111122111221211222112111210",
            time: 99,
            status: 0,
        },
        newName: "1-Fabiola",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "X9RZBzxqA4oY0NuiueHoMzLlGPqnNK",
            tie: 8,
            playerSide: 20,
            balance: 50020,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
];
