export const FakeDataNormalMatch = [
    {
        game: {
            gameId: 1027566,
            result: 2,
            playerSide: false,
            gameIdEncode: "BWA5SW",
            deckHistory: "2122221121112012202202",
            time: 7,
            banker: {
                Card: [
                    { face: "D", value: "K" },
                    { face: "D", value: 6 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "C", value: 4 },
                    { face: "H", value: "K" },
                    { face: "S", value: "Q" },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        action: "login",
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1828.7,
            maxSide: 30,
            commission: 5,
        },
        text: 312312,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027566,
            result: 2,
            playerSide: false,
            gameIdEncode: "BWA5SW",
            deckHistory: "2122221121112012202202",
            time: 6,
            banker: {
                Card: [
                    { face: "D", value: "K" },
                    { face: "D", value: 6 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "C", value: 4 },
                    { face: "H", value: "K" },
                    { face: "S", value: "Q" },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1828.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027566,
            result: 2,
            playerSide: false,
            gameIdEncode: "BWA5SW",
            deckHistory: "2122221121112012202202",
            time: 5,
            banker: {
                Card: [
                    { face: "D", value: "K" },
                    { face: "D", value: 6 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "C", value: 4 },
                    { face: "H", value: "K" },
                    { face: "S", value: "Q" },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1828.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027566,
            result: 2,
            playerSide: false,
            gameIdEncode: "BWA5SW",
            deckHistory: "2122221121112012202202",
            time: 4,
            banker: {
                Card: [
                    { face: "D", value: "K" },
                    { face: "D", value: 6 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "C", value: 4 },
                    { face: "H", value: "K" },
                    { face: "S", value: "Q" },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1828.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027566,
            result: 2,
            playerSide: false,
            gameIdEncode: "BWA5SW",
            deckHistory: "2122221121112012202202",
            time: 3,
            banker: {
                Card: [
                    { face: "D", value: "K" },
                    { face: "D", value: 6 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "C", value: 4 },
                    { face: "H", value: "K" },
                    { face: "S", value: "Q" },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1828.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027566,
            result: 2,
            playerSide: false,
            gameIdEncode: "BWA5SW",
            deckHistory: "2122221121112012202202",
            time: 2,
            banker: {
                Card: [
                    { face: "D", value: "K" },
                    { face: "D", value: 6 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "C", value: 4 },
                    { face: "H", value: "K" },
                    { face: "S", value: "Q" },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1828.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027566,
            result: 2,
            playerSide: false,
            gameIdEncode: "BWA5SW",
            deckHistory: "2122221121112012202202",
            time: 1,
            banker: {
                Card: [
                    { face: "D", value: "K" },
                    { face: "D", value: 6 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "C", value: 4 },
                    { face: "H", value: "K" },
                    { face: "S", value: "Q" },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1828.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027566,
            result: 2,
            playerSide: false,
            gameIdEncode: "BWA5SW",
            deckHistory: "2122221121112012202202",
            time: 0,
            banker: {
                Card: [
                    { face: "D", value: "K" },
                    { face: "D", value: 6 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "C", value: 4 },
                    { face: "H", value: "K" },
                    { face: "S", value: "Q" },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1828.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: 20,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1828.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: 19,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1828.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: 18,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1828.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: 17,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1828.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: 16,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1828.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: 15,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1828.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: 14,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1828.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: 13,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1828.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: 12,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1828.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: 11,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1828.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: 10,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1828.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: 9,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1828.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: 8,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1828.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: 7,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1828.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: 7,
            status: 0,
        },
        numOfPlayers: 0,
        action: "bet",
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1793.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
        },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: 6,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1793.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
        },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: 5,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1793.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
        },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: 4,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1793.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
        },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: 3,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1793.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
        },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: 2,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1793.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
        },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: 1,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1793.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
        },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: 0,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1793.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
        },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: -1,
            status: 1,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1793.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
        },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: -1,
            player: { Card: { face: "H", value: "K" } },
            status: 1,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1793.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
        },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: -1,
            banker: { Card: { face: "C", value: "A" } },
            player: { Card: { face: "H", value: "K" } },
            status: 1,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1793.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
        },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: -1,
            banker: { Card: { face: "C", value: "A" } },
            player: {
                Card: [
                    { face: "H", value: "K" },
                    { face: "D", value: 10 },
                ],
            },
            status: 1,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1793.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
        },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: -1,
            banker: {
                Card: [
                    { face: "C", value: "A" },
                    { face: "H", value: 10 },
                ],
            },
            player: {
                Card: [
                    { face: "H", value: "K" },
                    { face: "D", value: 10 },
                ],
            },
            status: 1,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1793.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
        },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: -1,
            banker: {
                Card: [
                    { face: "C", value: "A" },
                    { face: "H", value: 10 },
                ],
            },
            player: {
                Card: [
                    { face: "H", value: "K" },
                    { face: "D", value: 10 },
                    { face: "S", value: 7 },
                ],
            },
            status: 1,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1793.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
        },
    },
    {
        game: {
            gameId: 1027567,
            result: -2,
            gameIdEncode: "BWA5T5",
            deckHistory: "2122221121112012202202",
            time: -1,
            banker: {
                Card: [
                    { face: "C", value: "A" },
                    { face: "H", value: 10 },
                    { face: "H", value: 6 },
                ],
            },
            player: {
                Card: [
                    { face: "H", value: "K" },
                    { face: "D", value: 10 },
                    { face: "S", value: 7 },
                ],
            },
            status: 1,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1793.7,
            maxSide: 30,
            commission: 5,
        },
        text: 2804,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
        },
    },
    {
        game: {
            gameId: 1027567,
            result: 0,
            playerSide: false,
            gameIdEncode: "BWA5T5",
            deckHistory: "21222211211120122022020",
            time: -1,
            banker: {
                Card: [
                    { face: "C", value: "A" },
                    { face: "H", value: 10 },
                    { face: "H", value: 6 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "H", value: "K" },
                    { face: "D", value: 10 },
                    { face: "S", value: 7 },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        action: "result",
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
            finalResult: { lost: 10, won: 200, totalBet: 35, commission: 0, totalEarning: 190 },
        },
    },
    {
        game: {
            gameId: 1027567,
            result: 0,
            playerSide: false,
            gameIdEncode: "BWA5T5",
            deckHistory: "21222211211120122022020",
            time: 7,
            banker: {
                Card: [
                    { face: "C", value: "A" },
                    { face: "H", value: 10 },
                    { face: "H", value: 6 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "H", value: "K" },
                    { face: "D", value: 10 },
                    { face: "S", value: 7 },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
            finalResult: { lost: 10, won: 200, totalBet: 35, commission: 0, totalEarning: 190 },
        },
    },
    {
        game: {
            gameId: 1027567,
            result: 0,
            playerSide: false,
            gameIdEncode: "BWA5T5",
            deckHistory: "21222211211120122022020",
            time: 6,
            banker: {
                Card: [
                    { face: "C", value: "A" },
                    { face: "H", value: 10 },
                    { face: "H", value: 6 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "H", value: "K" },
                    { face: "D", value: 10 },
                    { face: "S", value: 7 },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
            finalResult: { lost: 10, won: 200, totalBet: 35, commission: 0, totalEarning: 190 },
        },
    },
    {
        game: {
            gameId: 1027567,
            result: 0,
            playerSide: false,
            gameIdEncode: "BWA5T5",
            deckHistory: "21222211211120122022020",
            time: 5,
            banker: {
                Card: [
                    { face: "C", value: "A" },
                    { face: "H", value: 10 },
                    { face: "H", value: 6 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "H", value: "K" },
                    { face: "D", value: 10 },
                    { face: "S", value: 7 },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
            finalResult: { lost: 10, won: 200, totalBet: 35, commission: 0, totalEarning: 190 },
        },
    },
    {
        game: {
            gameId: 1027567,
            result: 0,
            playerSide: false,
            gameIdEncode: "BWA5T5",
            deckHistory: "21222211211120122022020",
            time: 4,
            banker: {
                Card: [
                    { face: "C", value: "A" },
                    { face: "H", value: 10 },
                    { face: "H", value: 6 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "H", value: "K" },
                    { face: "D", value: 10 },
                    { face: "S", value: 7 },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
            finalResult: { lost: 10, won: 200, totalBet: 35, commission: 0, totalEarning: 190 },
        },
    },
    {
        game: {
            gameId: 1027567,
            result: 0,
            playerSide: false,
            gameIdEncode: "BWA5T5",
            deckHistory: "21222211211120122022020",
            time: 3,
            banker: {
                Card: [
                    { face: "C", value: "A" },
                    { face: "H", value: 10 },
                    { face: "H", value: 6 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "H", value: "K" },
                    { face: "D", value: 10 },
                    { face: "S", value: 7 },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
            finalResult: { lost: 10, won: 200, totalBet: 35, commission: 0, totalEarning: 190 },
        },
    },
    {
        game: {
            gameId: 1027567,
            result: 0,
            playerSide: false,
            gameIdEncode: "BWA5T5",
            deckHistory: "21222211211120122022020",
            time: 2,
            banker: {
                Card: [
                    { face: "C", value: "A" },
                    { face: "H", value: 10 },
                    { face: "H", value: 6 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "H", value: "K" },
                    { face: "D", value: 10 },
                    { face: "S", value: 7 },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
            finalResult: { lost: 10, won: 200, totalBet: 35, commission: 0, totalEarning: 190 },
        },
    },
    {
        game: {
            gameId: 1027567,
            result: 0,
            playerSide: false,
            gameIdEncode: "BWA5T5",
            deckHistory: "21222211211120122022020",
            time: 1,
            banker: {
                Card: [
                    { face: "C", value: "A" },
                    { face: "H", value: 10 },
                    { face: "H", value: 6 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "H", value: "K" },
                    { face: "D", value: 10 },
                    { face: "S", value: 7 },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
            finalResult: { lost: 10, won: 200, totalBet: 35, commission: 0, totalEarning: 190 },
        },
    },
    {
        game: {
            gameId: 1027567,
            result: 0,
            playerSide: false,
            gameIdEncode: "BWA5T5",
            deckHistory: "21222211211120122022020",
            time: 0,
            banker: {
                Card: [
                    { face: "C", value: "A" },
                    { face: "H", value: 10 },
                    { face: "H", value: 6 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "H", value: "K" },
                    { face: "D", value: 10 },
                    { face: "S", value: 7 },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: {
                bet: [
                    { result: -2, amount: 25, betOn: 0, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 3, diff: 0, type: "fun", username: "ptest1" },
                    { result: -2, amount: 5, betOn: 4, diff: 0, type: "fun", username: "ptest1" },
                ],
            },
            finalResult: { lost: 10, won: 200, totalBet: 35, commission: 0, totalEarning: 190 },
        },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: 20,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: 19,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: 18,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: 17,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: 16,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: 15,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: 14,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: 13,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: 12,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: 11,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: 10,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: 9,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: 8,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: 7,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: 6,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: 5,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: 4,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: 3,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: 2,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: 1,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 2018.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: 0,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: { bet: { result: -2, amount: 25, betOn: 2, diff: 0, type: "fun", username: "ptest1" } } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: -1,
            status: 1,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: { bet: { result: -2, amount: 25, betOn: 2, diff: 0, type: "fun", username: "ptest1" } } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: -1,
            player: { Card: { face: "D", value: 10 } },
            status: 1,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: { bet: { result: -2, amount: 25, betOn: 2, diff: 0, type: "fun", username: "ptest1" } } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: -1,
            banker: { Card: { face: "D", value: 3 } },
            player: { Card: { face: "D", value: 10 } },
            status: 1,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: { bet: { result: -2, amount: 25, betOn: 2, diff: 0, type: "fun", username: "ptest1" } } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: -1,
            banker: { Card: { face: "D", value: 3 } },
            player: {
                Card: [
                    { face: "D", value: 10 },
                    { face: "S", value: 5 },
                ],
            },
            status: 1,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: { bet: { result: -2, amount: 25, betOn: 2, diff: 0, type: "fun", username: "ptest1" } } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: -1,
            banker: {
                Card: [
                    { face: "D", value: 3 },
                    { face: "D", value: 8 },
                ],
            },
            player: {
                Card: [
                    { face: "D", value: 10 },
                    { face: "S", value: 5 },
                ],
            },
            status: 1,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: { bet: { result: -2, amount: 25, betOn: 2, diff: 0, type: "fun", username: "ptest1" } } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: -1,
            banker: {
                Card: [
                    { face: "D", value: 3 },
                    { face: "D", value: 8 },
                ],
            },
            player: {
                Card: [
                    { face: "D", value: 10 },
                    { face: "S", value: 5 },
                    { face: "C", value: "Q" },
                ],
            },
            status: 1,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: { bet: { result: -2, amount: 25, betOn: 2, diff: 0, type: "fun", username: "ptest1" } } },
    },
    {
        game: {
            gameId: 1027568,
            result: -2,
            gameIdEncode: "BWA5U4",
            deckHistory: "21222211211120122022020",
            time: -1,
            banker: {
                Card: [
                    { face: "D", value: 3 },
                    { face: "D", value: 8 },
                    { face: "S", value: 9 },
                ],
            },
            player: {
                Card: [
                    { face: "D", value: 10 },
                    { face: "S", value: 5 },
                    { face: "C", value: "Q" },
                ],
            },
            status: 1,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 2804,
        gameSession: { bets: { bet: { result: -2, amount: 25, betOn: 2, diff: 0, type: "fun", username: "ptest1" } } },
    },
    {
        game: {
            gameId: 1027568,
            result: 1,
            playerSide: false,
            gameIdEncode: "BWA5U4",
            deckHistory: "212222112111201220220201",
            time: -1,
            banker: {
                Card: [
                    { face: "D", value: 3 },
                    { face: "D", value: 8 },
                    { face: "S", value: 9 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "D", value: 10 },
                    { face: "S", value: 5 },
                    { face: "C", value: "Q" },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        action: "result",
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: { bet: { result: -2, amount: 25, betOn: 2, diff: 0, type: "fun", username: "ptest1" } },
            finalResult: { lost: 25, won: 0, totalBet: 25, commission: 0, totalEarning: -25 },
        },
    },
    {
        game: {
            gameId: 1027568,
            result: 1,
            playerSide: false,
            gameIdEncode: "BWA5U4",
            deckHistory: "212222112111201220220201",
            time: 7,
            banker: {
                Card: [
                    { face: "D", value: 3 },
                    { face: "D", value: 8 },
                    { face: "S", value: 9 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "D", value: 10 },
                    { face: "S", value: 5 },
                    { face: "C", value: "Q" },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: { bet: { result: -2, amount: 25, betOn: 2, diff: 0, type: "fun", username: "ptest1" } },
            finalResult: { lost: 25, won: 0, totalBet: 25, commission: 0, totalEarning: -25 },
        },
    },
    {
        game: {
            gameId: 1027568,
            result: 1,
            playerSide: false,
            gameIdEncode: "BWA5U4",
            deckHistory: "212222112111201220220201",
            time: 6,
            banker: {
                Card: [
                    { face: "D", value: 3 },
                    { face: "D", value: 8 },
                    { face: "S", value: 9 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "D", value: 10 },
                    { face: "S", value: 5 },
                    { face: "C", value: "Q" },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: { bet: { result: -2, amount: 25, betOn: 2, diff: 0, type: "fun", username: "ptest1" } },
            finalResult: { lost: 25, won: 0, totalBet: 25, commission: 0, totalEarning: -25 },
        },
    },
    {
        game: {
            gameId: 1027568,
            result: 1,
            playerSide: false,
            gameIdEncode: "BWA5U4",
            deckHistory: "212222112111201220220201",
            time: 5,
            banker: {
                Card: [
                    { face: "D", value: 3 },
                    { face: "D", value: 8 },
                    { face: "S", value: 9 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "D", value: 10 },
                    { face: "S", value: 5 },
                    { face: "C", value: "Q" },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: { bet: { result: -2, amount: 25, betOn: 2, diff: 0, type: "fun", username: "ptest1" } },
            finalResult: { lost: 25, won: 0, totalBet: 25, commission: 0, totalEarning: -25 },
        },
    },
    {
        game: {
            gameId: 1027568,
            result: 1,
            playerSide: false,
            gameIdEncode: "BWA5U4",
            deckHistory: "212222112111201220220201",
            time: 4,
            banker: {
                Card: [
                    { face: "D", value: 3 },
                    { face: "D", value: 8 },
                    { face: "S", value: 9 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "D", value: 10 },
                    { face: "S", value: 5 },
                    { face: "C", value: "Q" },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: { bet: { result: -2, amount: 25, betOn: 2, diff: 0, type: "fun", username: "ptest1" } },
            finalResult: { lost: 25, won: 0, totalBet: 25, commission: 0, totalEarning: -25 },
        },
    },
    {
        game: {
            gameId: 1027568,
            result: 1,
            playerSide: false,
            gameIdEncode: "BWA5U4",
            deckHistory: "212222112111201220220201",
            time: 3,
            banker: {
                Card: [
                    { face: "D", value: 3 },
                    { face: "D", value: 8 },
                    { face: "S", value: 9 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "D", value: 10 },
                    { face: "S", value: 5 },
                    { face: "C", value: "Q" },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: { bet: { result: -2, amount: 25, betOn: 2, diff: 0, type: "fun", username: "ptest1" } },
            finalResult: { lost: 25, won: 0, totalBet: 25, commission: 0, totalEarning: -25 },
        },
    },
    {
        game: {
            gameId: 1027568,
            result: 1,
            playerSide: false,
            gameIdEncode: "BWA5U4",
            deckHistory: "212222112111201220220201",
            time: 2,
            banker: {
                Card: [
                    { face: "D", value: 3 },
                    { face: "D", value: 8 },
                    { face: "S", value: 9 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "D", value: 10 },
                    { face: "S", value: 5 },
                    { face: "C", value: "Q" },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: { bet: { result: -2, amount: 25, betOn: 2, diff: 0, type: "fun", username: "ptest1" } },
            finalResult: { lost: 25, won: 0, totalBet: 25, commission: 0, totalEarning: -25 },
        },
    },
    {
        game: {
            gameId: 1027568,
            result: 1,
            playerSide: false,
            gameIdEncode: "BWA5U4",
            deckHistory: "212222112111201220220201",
            time: 1,
            banker: {
                Card: [
                    { face: "D", value: 3 },
                    { face: "D", value: 8 },
                    { face: "S", value: 9 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "D", value: 10 },
                    { face: "S", value: 5 },
                    { face: "C", value: "Q" },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: { bet: { result: -2, amount: 25, betOn: 2, diff: 0, type: "fun", username: "ptest1" } },
            finalResult: { lost: 25, won: 0, totalBet: 25, commission: 0, totalEarning: -25 },
        },
    },
    {
        game: {
            gameId: 1027568,
            result: 1,
            playerSide: false,
            gameIdEncode: "BWA5U4",
            deckHistory: "212222112111201220220201",
            time: 0,
            banker: {
                Card: [
                    { face: "D", value: 3 },
                    { face: "D", value: 8 },
                    { face: "S", value: 9 },
                ],
            },
            bankerSide: false,
            player: {
                Card: [
                    { face: "D", value: 10 },
                    { face: "S", value: 5 },
                    { face: "C", value: "Q" },
                ],
            },
            status: 2,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: {
            bets: { bet: { result: -2, amount: 25, betOn: 2, diff: 0, type: "fun", username: "ptest1" } },
            finalResult: { lost: 25, won: 0, totalBet: 25, commission: 0, totalEarning: -25 },
        },
    },
    {
        game: {
            gameId: 1027569,
            result: -2,
            gameIdEncode: "BWA5VQ",
            deckHistory: "212222112111201220220201",
            time: 20,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027569,
            result: -2,
            gameIdEncode: "BWA5VQ",
            deckHistory: "212222112111201220220201",
            time: 19,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027569,
            result: -2,
            gameIdEncode: "BWA5VQ",
            deckHistory: "212222112111201220220201",
            time: 18,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027569,
            result: -2,
            gameIdEncode: "BWA5VQ",
            deckHistory: "212222112111201220220201",
            time: 17,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027569,
            result: -2,
            gameIdEncode: "BWA5VQ",
            deckHistory: "212222112111201220220201",
            time: 16,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027569,
            result: -2,
            gameIdEncode: "BWA5VQ",
            deckHistory: "212222112111201220220201",
            time: 15,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
    {
        game: {
            gameId: 1027569,
            result: -2,
            gameIdEncode: "BWA5VQ",
            deckHistory: "212222112111201220220201",
            time: 14,
            status: 0,
        },
        newName: "7-Maricel",
        numOfPlayers: 3,
        userSession: {
            minSide: 1,
            maxTie: 60,
            maxBet: 300,
            minBet: 5,
            minTie: 1,
            userName: "ptest1",
            bankerSide: 30,
            sid: "n7vcqgCxHzsotHr9ZMPo09ewXHg2El",
            tie: 8,
            playerSide: 20,
            balance: 1993.7,
            maxSide: 30,
            commission: 5,
        },
        text: 100,
        gameSession: { bets: "", finalResult: { lost: 0, won: 0, totalBet: 0, commission: 0, totalEarning: 0 } },
    },
];
